FROM nginx:1.27-alpine

COPY docker/app-showcase/index.html /usr/share/nginx/html/index.html
COPY LICENSE /usr/share/nginx/html/LICENSE
COPY docs /usr/share/nginx/html/docs
COPY release-artifacts /usr/share/nginx/html/release-artifacts
